### PR TITLE
build: add -Wall -Werror to CI build

### PR DESCRIPTION
**Pull request by danbev**
This commit adds build flags to CMake to enable all warnings and to turn
warnings into errors.

### CODE REVIEW

**Comment by danbev** [comment]
@cjihrig Would something like this be enough for CI (minus the last commit which is just to show that it fails upon a warnings).

**Comment by cjihrig** [comment]
I think so. It would be good to do something similar on Windows at some point, since it has the most platform specific code.

**Comment by cjihrig** [comment]
@danbev are you still planning to work on this?

**Comment by danbev** [comment]
I’m on PTO at the moment and won’t be back for another 3 weeks.

But I still don’t have a windows env to try getting the same thing working
on windows.

Perhaps this PR could be merged without that as it would at least fail on
warnings for Unix environments? If not feel free to close this and I might
revisit I when I get back.

lör 25 juli 2020 kl. 17:06 skrev Colin Ihrig <notifications@github.com>:

**Comment by cjihrig** [comment]
I think this can land without Windows support. Can you take it out of draft status and get the CI passing (I think you just have an extra test commit)?

**Pull request merged**
