### PR TITLE
test: initial configuration of check

### PR DESCRIPTION
**Pull request by danbev**
This commit adds a configuration for using check as the unit testing
framework.

### CODE REVIEW

**Comment by danbev** [comment]
This currently does not tests against uvwasi, it just has some bogus asserts. Just wanted to open this up for feedback if `check` seems like worth pursuing further.

**Comment by cjihrig** [comment]
This seems like a good start to be. I'll install check a bit later and actually test it out, but in general, I'm good with this.

**Comment by danbev** [comment]
@cjihrig I noticed the addition of tests to master, should we abandon this work?

**Comment by cjihrig** [comment]
I think since we've moved to cmake anyway for a better cross-platform story, it probably makes sense to leverage the built in test runner. If `Check` (or any other test framework) has features that we could really use, then I'm definitely not opposed to using it, but it's nice to have one less external dependency.

**Comment by danbev** [comment]
> If `Check` (or any other test framework) has features that we could really use, then I'm definitely not opposed to using it, but it's nice to have one less external dependency.

Sounds good with one less dependency and let's see if there are features a test framework would provide once there is a need for them 👍

**Pull request closed without merging**
